project:
  type: website
  output-dir: docs

website:
  title: "Avian Information Landscapes"
  navbar:
    collapse: true
    collapse-below: lg
    toggle-position: right
    left:
      - href: index.qmd
        text: About Me
      - href: publications.qmd
        text: Publications
      - href: research.qmd
        text: Research
      - href: media.qmd
        text: Media

format:
  html:
    theme:
      - cosmo
      - styles.scss
    include-in-header: google-verification.html
